I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 116, in script
    $ postavi_pitanje(pitanje)
  File "game/script.rpy", line 116, in <module>
    $ postavi_pitanje(pitanje)
  File "game/script.rpy", line 62, in postavi_pitanje
    trenutno_pitanje = random.choice(odabrana_pitanja)
TypeError: object of type 'Pitanje' has no len()

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 116, in script
    $ postavi_pitanje(pitanje)
  File "renpy/ast.py", line 823, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 116, in <module>
    $ postavi_pitanje(pitanje)
  File "game/script.rpy", line 62, in postavi_pitanje
    trenutno_pitanje = random.choice(odabrana_pitanja)
  File "lib/python2.7/random.py", line 277, in choice
TypeError: object of type 'Pitanje' has no len()

Windows-10-10.0.19041 AMD64
Ren'Py 7.7.3.24061702
Kviz 1.0
Sat Jan 11 14:09:18 2025
